// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiIgJqwyAw9HUioudRLWby55N33V87Z6M',
    appId: '1:189103617459:web:4bbc39ab8d78dc2340c7c6',
    messagingSenderId: '189103617459',
    projectId: 'ghost-butler-9a43a',
    authDomain: 'ghost-butler-9a43a.firebaseapp.com',
    storageBucket: 'ghost-butler-9a43a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9FinXfay99QIet3rJ-a10KjAjvyKsEvI',
    appId: '1:189103617459:android:59471c7c4416d72240c7c6',
    messagingSenderId: '189103617459',
    projectId: 'ghost-butler-9a43a',
    storageBucket: 'ghost-butler-9a43a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB51Bc6qN9W5-uiTgagAr8QByUGKvfuvx0',
    appId: '1:189103617459:ios:1721a05cf3f27e2940c7c6',
    messagingSenderId: '189103617459',
    projectId: 'ghost-butler-9a43a',
    storageBucket: 'ghost-butler-9a43a.appspot.com',
    iosClientId: '189103617459-2v8r9tv7fscrjvqkthqeblgfiilocm33.apps.googleusercontent.com',
    iosBundleId: 'ghostButler1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB51Bc6qN9W5-uiTgagAr8QByUGKvfuvx0',
    appId: '1:189103617459:ios:64e8d591930d21f740c7c6',
    messagingSenderId: '189103617459',
    projectId: 'ghost-butler-9a43a',
    storageBucket: 'ghost-butler-9a43a.appspot.com',
    iosClientId: '189103617459-kgao8bpsud2i1g3lpa001fpeshlcki1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghostButler.RunnerTests',
  );
}
