// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-A7uzCX-TswM2oLWEaDe3p46Z3GV6stA',
    appId: '1:378871415635:web:7e40a8315f12064c07d7a6',
    messagingSenderId: '378871415635',
    projectId: 'codelab-firebase-97641',
    authDomain: 'codelab-firebase-97641.firebaseapp.com',
    databaseURL: 'https://codelab-firebase-97641-default-rtdb.firebaseio.com',
    storageBucket: 'codelab-firebase-97641.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY4MgmmCwmDgVE5YpEvdXr-61NqHLAliw',
    appId: '1:378871415635:android:d15347bf6b505d9007d7a6',
    messagingSenderId: '378871415635',
    projectId: 'codelab-firebase-97641',
    databaseURL: 'https://codelab-firebase-97641-default-rtdb.firebaseio.com',
    storageBucket: 'codelab-firebase-97641.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu66YamU5BY_6FNOR9qhT3d0RJP4NqD28',
    appId: '1:378871415635:ios:09dbdba6d75cf58407d7a6',
    messagingSenderId: '378871415635',
    projectId: 'codelab-firebase-97641',
    databaseURL: 'https://codelab-firebase-97641-default-rtdb.firebaseio.com',
    storageBucket: 'codelab-firebase-97641.appspot.com',
    iosBundleId: 'com.example.ghostButler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu66YamU5BY_6FNOR9qhT3d0RJP4NqD28',
    appId: '1:378871415635:ios:1518d95019973b6d07d7a6',
    messagingSenderId: '378871415635',
    projectId: 'codelab-firebase-97641',
    databaseURL: 'https://codelab-firebase-97641-default-rtdb.firebaseio.com',
    storageBucket: 'codelab-firebase-97641.appspot.com',
    iosBundleId: 'com.example.ghostButler.RunnerTests',
  );
}
